version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1 --reload"
    environment:
      - PYTHONUNBUFFERED=1
